---
author: Ryan Grimm

custom_categories:
- name: Client
  children:
  - ElasticsearchClient
  - ElasticsearchIndex
  - ElasticsearchDatabase
  - ElasticsearchProvider
  - ElasticsearchClientConfig

- name: Query Constructors
  children:
  - BoolQuery
  - CommonTerms
  - Exists
  - Fuzzy
  - IDs
  - Match
  - MatchAll
  - MatchNone
  - MatchPhrase
  - MatchPhrasePrefix
  - MultiMatch
  - Prefix
  - Query
  - Range
  - Regexp
  - ScriptQuery
  - Term
  - Terms
  - Wildcard
  - SpanQuery
  - SpanTerm
  - SpanFirst
  - SpanNot
  - SpanOr
  - SpanNear
  - SpanContaining
  - SpanWithin
  - GeoPolygon
- name: Aggregation Constructors
  children:
  - MinAggregation
  - SumAggregation
  - StatsAggregation
  - MaxAggregation
  - AvgAggregation
  - GeoCentroidAggregation
  - GeoBoundsAggregation
  - TopHitsAggregation
  - CardinalityAggregation
  - ValueCountAggregation
  - ExtendedStatsAggregation
  - TermsAggregation
- name: Response Structures
  children:
  - AggregationExtendedStatsResponse
  - AggregationGeoBoundsResponse
  - AggregationGeoCentroidResponse
  - AggregationResponse
  - AggregationSingleValueResponse
  - AggregationStatsResponse
  - AggregationTermsResponse
  - DocResponse
  - IndexResponse
  - SearchResponse
- name: Index Mapping
  children:
  - IndexSettings
  - MapBinary
  - MapBoolean
  - MapByte
  - MapCompletionSuggester
  - MapDate
  - MapDateRange
  - MapDouble
  - MapDoubleRange
  - MapFloat
  - MapFloatRange
  - MapGeoPoint
  - MapGeoShape
  - MapHalfFloat
  - MapIPAddress
  - MapInteger
  - MapIntegerRange
  - MapJoin
  - MapKeyword
  - MapLong
  - MapLongRange
  - MapNested
  - MapObject
  - MapPercolator
  - MapScaledFloat
  - MapShort
  - MapText
  - MapTokenCount
- name: Supporting Structures
  children:
  - Operator
  - OrderDirection
  - TextField
  - TextFieldType
  - TermVector
  - SimilarityType
  - TextIndexOptions
  - GeoValidationMethod
  - GeoPoint
  - Script
  - AggregationBucket
